from src.data_model.data_elements import DataElement
from src.data_model.value_set import ValueSet
from src.data_model.base_types import CodeSystem, Coding, Date, Code, String
from src.data_model.codesystems import CodeSystems

# Define CodeSystems
SNOMED = CodeSystems.SNOMED
HL7FHIR = CodeSystems.HL7FHIR
GA4GH = CodeSystems.GA4GH


class DATA_ELEMENTS_VERSIONS_V2_0_0:
    """Data elements definitions for version 2_0_0."""

    data_elements = [
        DataElement(
            ordinal="1.1",
            section="1. Formal Criteria",
            elementName="Pseudonym",
            elementCode=Coding(system=SNOMED, code="422549004"),
            elementCodeSystem=SNOMED,
            dataType="Identifier",
            dataSpecification=["n/a"],
            valueSet=None,
            fhirExpression_v4_0_1="Patient.identifier.value",
            recommendedDataSpec_fhir="n/a",
            phenopacketSchemaElement_v2_0="Individual.id",
            recommendedDataSpec_phenopackets="string",
            description="The (local) patient-related identification code."
        ),
        DataElement(
            ordinal="1.2",
            section="1. Formal Criteria",
            elementName="Date of Admission",
            elementCode=Coding(system=SNOMED, code="399423000"),
            elementCodeSystem=SNOMED,
            dataType=Date,
            dataSpecification=["YYYY-MM-DD"],
            valueSet=None,
            fhirExpression_v4_0_1="Encounter.period.start",
            recommendedDataSpec_fhir="n/a",
            phenopacketSchemaElement_v2_0="Individual.time_at_last_encounter",
            recommendedDataSpec_phenopackets="TimeElement",
            description="The date of admission or data capture of the individual."
        ),
        DataElement(
            ordinal="2.1",
            section="2. Personal Information",
            elementName="Date of Birth",
            elementCode=Coding(system=SNOMED, code="184099003"),
            elementCodeSystem=SNOMED,
            dataType=Date,
            dataSpecification=["YYYY", "YYYY-MM", "YYYY-MM-DD"],
            valueSet=None,
            fhirExpression_v4_0_1="Patient.birthDate",
            recommendedDataSpec_fhir="n/a",
            phenopacketSchemaElement_v2_0="Individual.date_of_birth",
            recommendedDataSpec_phenopackets="TimeElement",
            description="The individual's date of birth."
        ),
        DataElement(
            ordinal="2.2",
            section="2. Personal Information",
            elementName="Sex at Birth",
            elementCode=Coding(system=SNOMED, code="281053000"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["VSe / VSc"],
            valueSet="Sex at Birth Value Set v2.0.0",
            fhirExpression_v4_0_1="Patient.extension:individual-recordedSexOrGender",
            recommendedDataSpec_fhir="Recorded Sex Or Gender Type",
            phenopacketSchemaElement_v2_0="Individual.sex",
            recommendedDataSpec_phenopackets="Sex",
            description="The individual's sex that was assigned at birth."
        ),
        DataElement(
            ordinal="2.3",
            section="2. Personal Information",
            elementName="Karyotypic Sex",
            elementCode=Coding(system=SNOMED, code="1296886006"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["VSc"],
            valueSet="Karyotypic Sex Value Set v2.0.0",
            fhirExpression_v4_0_1="Observation.value",
            recommendedDataSpec_fhir="n/a",
            phenopacketSchemaElement_v2_0="Individual.karyotypic_sex",
            recommendedDataSpec_phenopackets="Karyotypic Sex",
            description="The chromosomal sex of an individual."
        ),
        DataElement(
            ordinal="2.4",
            section="2. Personal Information",
            elementName="Gender Identity",
            elementCode=Coding(system=SNOMED, code="263495000"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["VSe / VSc"],
            valueSet="Gender Identity Value Set v2.0.0",
            fhirExpression_v4_0_1="Patient.extension:individual-genderIdentity",
            recommendedDataSpec_fhir="Gender Identity",
            phenopacketSchemaElement_v2_0="Individual.gender",
            recommendedDataSpec_phenopackets="OntologyClass",
            description="The self-assigned gender of the individual."
        ),
        DataElement(
            ordinal="2.5",
            section="2. Personal Information",
            elementName="Country of Birth",
            elementCode=Coding(system=SNOMED, code="370159000"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["VS"],
            valueSet=None,  
            fhirExpression_v4_0_1="Patient.extension:patient-birthPlace",
            recommendedDataSpec_fhir="DataType: Address",
            phenopacketSchemaElement_v2_0="n/a",
            recommendedDataSpec_phenopackets="n/a",
            description="The individual's country of birth."
        ),
        # Section 3: Patient Status
        DataElement(
            ordinal="3.1",
            section="3. Patient Status",
            elementName="Vital Status",
            elementCode=Coding(system=SNOMED, code="278844005"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["VSe / VSc"],
            valueSet="Vital Status Value Set v2.0.0",
            fhirExpression_v4_0_1="Patient.deceased.deceasedBoolean|Observation.value",
            recommendedDataSpec_fhir="Boolean|Code",
            phenopacketSchemaElement_v2_0="Individual.VitalStatus.status",
            recommendedDataSpec_phenopackets="Value Set: Status",
            description="The individual’s general clinical status or vital status."
        ),
        DataElement(
            ordinal="3.2",
            section="3. Patient Status",
            elementName="Time of Death",
            elementCode=Coding(system=SNOMED, code="398299004"),
            elementCodeSystem=SNOMED,
            dataType=Date,
            dataSpecification=["YYYY", "YYYY-MM", "YYYY-MM-DD"],
            valueSet=None,
            fhirExpression_v4_0_1="Patient.deceasedDateTime",
            recommendedDataSpec_fhir="DateTime",
            phenopacketSchemaElement_v2_0="Individual.VitalStatus.time_of_death",
            recommendedDataSpec_phenopackets="TimeElement",
            description="If deceased, the individual’s date of death."
        ),
        DataElement(
            ordinal="3.3",
            section="3. Patient Status",
            elementName="Cause of Death",
            elementCode=Coding(system=SNOMED, code="184305005"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["ICD-10CM"],
            valueSet=None,
            fhirExpression_v4_0_1="Observation.value.coding.code",
            recommendedDataSpec_fhir="Code|CodeableConcept",
            phenopacketSchemaElement_v2_0="Individual.VitalStatus.cause_of_death",
            recommendedDataSpec_phenopackets="OntologyClass",
            description="If deceased, the individual’s primary cause of death."
        ),
        DataElement(
            ordinal="3.4",
            section="3. Patient Status",
            elementName="Age Category",
            elementCode=Coding(system=SNOMED, code="105727008"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["VSe"],
            valueSet="Age Category Value Set v2.0.0", 
            fhirExpression_v4_0_1="Observation.value.coding.code",
            recommendedDataSpec_fhir="CodableConcept",
            phenopacketSchemaElement_v2_0="Individual.time_at_last_encounter.ontology_class",
            recommendedDataSpec_phenopackets="TimeElement",
            description="The individual's age category at the time of data capture."
        ),
        DataElement(
            ordinal="3.5",
            section="3. Patient Status",
            elementName="Length of Gestation at Birth [weeks+days]",
            elementCode=Coding(system=SNOMED, code="412726003"),
            elementCodeSystem=SNOMED,
            dataType=String,
            dataSpecification=["XX+X"],
            valueSet=None,
            fhirExpression_v4_0_1="Observation.component:weeks.valueQuantity|Observation.component:days.valueQuantity",
            recommendedDataSpec_fhir="Quantity",
            phenopacketSchemaElement_v2_0="n/a",
            recommendedDataSpec_phenopackets="n/a",
            description="The duration of the pregnancy in weeks and days, formatted as XX+X (weeks+days)."
        ),
        DataElement(
            ordinal="3.6",
            section="3. Patient Status",
            elementName="Undiagnosed RD Case",
            elementCode=Coding(system=SNOMED, code="723663001"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["VSe"],
            valueSet="Undiagnosed RD Case Value Set v2.0.0",
            fhirExpression_v4_0_1="(Condition.code)",
            recommendedDataSpec_fhir="Code(e.g. ORDO:616874 - Rare disorder without a determined diagnosis after full investigation)",
            phenopacketSchemaElement_v2_0="(Disease.term)",
            recommendedDataSpec_phenopackets="(OntologyClass (e.g. ORDO:616874 - Rare disorder without a determined diagnosis after full investigation))",
            description="Identifies cases where an RD diagnosis has not been established."
        ),
        DataElement(
            ordinal="4.1",
            section="4. Care Pathway",
            elementName="Encounter Start",
            elementCode=Coding(system=HL7FHIR, code="encounter.period.start"),
            elementCodeSystem=HL7FHIR,
            dataType=Date,
            dataSpecification=["YYYY-MM-DD"],
            valueSet=None,
            fhirExpression_v4_0_1="Encounter.period.start",
            recommendedDataSpec_fhir="DateTime",
            phenopacketSchemaElement_v2_0="n/a",
            recommendedDataSpec_phenopackets="n/a",
            description="The beginning of an encounter of the individual."
        ),
        DataElement(
            ordinal="4.2",
            section="4. Care Pathway",
            elementName="Encounter End",
            elementCode=Coding(system=HL7FHIR, code="encounter.period.end"),
            elementCodeSystem=HL7FHIR,
            dataType=Date,
            dataSpecification=["YYYY-MM-DD"],
            valueSet=None,
            fhirExpression_v4_0_1="Encounter.period.end",
            recommendedDataSpec_fhir="DateTime",
            phenopacketSchemaElement_v2_0="n/a",
            recommendedDataSpec_phenopackets="n/a",
            description="The end of an encounter of the individual."
        ),
        DataElement(
            ordinal="4.3",
            section="4. Care Pathway",
            elementName="Encounter Status",
            elementCode=Coding(system=SNOMED, code="305058001"),
            elementCodeSystem=SNOMED,
            dataType=Code,
            dataSpecification=["VSe / VSc"],
            valueSet="Encounter Status Value Set v2.0.0",
            fhirExpression_v4_0_1="Encounter.status",
            recommendedDataSpec_fhir="ValueSet: EncounterStatus",
            phenopacketSchemaElement_v2_0="n/a",
            recommendedDataSpec_phenopackets="n/a",
            description="The status of an encounter of the individual at the time of data capture."
        ),
        DataElement(
            ordinal="4.4",
            section="4. Care Pathway",
            elementName="Encounter Class",
            elementCode=Coding(system=HL7FHIR, code="encounter.class"),
            elementCodeSystem=HL7FHIR,
            dataType=Code,
            dataSpecification=["VSe / VSc"],
            valueSet="Encounter Class Value Set v2.0.0",
            fhirExpression_v4_0_1="Encounter.class",
            recommendedDataSpec_fhir="ValueSet: EncounterClass",
            phenopacketSchemaElement_v2_0="n/a",
            recommendedDataSpec_phenopackets="n/a",
            description="The class of an encounter of the individual at the time of data capture."
        )
    ]
