# AUTO-GENERATED by src/rd_cdm/utils/gen_pydantic.py (PydanticGenerator)
# Schema: /Users/adamgraefe/Documents/git/rd-cdm/src/rd_cdm/schema/rd_cdm.yaml
# Do not edit manually — re-run gen_pydantic.py to regenerate.

from __future__ import annotations

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal
from enum import Enum
from typing import (
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer
)


metamodel_version = "1.11.0"
version = "2.1.0"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        serialize_by_alias = True,
        validate_by_name = True,
        validate_assignment = True,
        validate_default = True,
        extra = "forbid",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )





class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta({'default_prefix': 'https://github.com/BIH-CEI/rd-cdm/linkml/rd_cdm.schema.yaml/',
     'id': 'https://github.com/BIH-CEI/rd-cdm/linkml/rd_cdm.schema.yaml',
     'imports': ['linkml:types'],
     'license': 'CC0',
     'name': 'rd-cdm',
     'prefixes': {'linkml': {'prefix_prefix': 'linkml',
                             'prefix_reference': 'https://w3id.org/linkml/'},
                  'rdcdm': {'prefix_prefix': 'rdcdm',
                            'prefix_reference': 'https://github.com/BIH-CEI/rd-cdm/'},
                  'xsd': {'prefix_prefix': 'xsd',
                          'prefix_reference': 'http://www.w3.org/2001/XMLSchema#'}},
     'source_file': '/var/folders/dw/90nzwf496hz_c9v0gprb4_s40000gn/T/tmpy6w9czgd.yaml',
     'title': 'ontology-based rare disease common data model (RD-CDM) harmonising '
              'international registries, FHIR, and Phenopackets'} )

class CodeStatus(str, Enum):
    """
    Whether a code still resolves against BioPortal, the single terminology authority this model validates against.

    """
    active = "active"
    """
    The code resolves. This is the default and is not written out explicitly.

    """
    inactive = "inactive"
    """
    The code no longer resolves in BioPortal. Not available for new data capture - use `replacedBy` instead - but retained so that data already captured against it stays interpretable. `rd-cdm-validate` reports it as a known inactivation rather than an error, and warns if it starts resolving again.

    """



class RdCdm(ConfiguredBaseModel):
    """
    Root class for the Rare Disease Common Data Model (RD-CDM)
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://github.com/BIH-CEI/rd-cdm/linkml/rd_cdm.schema.yaml',
         'tree_root': True})

    rd_cdm_version: str = Field(default=..., description="""Version of the RD-CDM schema""", json_schema_extra = { "linkml_meta": {'domain_of': ['RdCdm']} })
    rd_cdm_date: date = Field(default=..., description="""Date of the RD-CDM release""", json_schema_extra = { "linkml_meta": {'domain_of': ['RdCdm']} })
    code_systems: Optional[list[CodeSystem]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['RdCdm']} })
    data_elements: Optional[list[DataElement]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['RdCdm']} })
    value_sets: Optional[list[ValueSet]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['RdCdm']} })


class CodeSystem(ConfiguredBaseModel):
    """
    Metadata for an ontology or code system
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://github.com/BIH-CEI/rd-cdm/linkml/rd_cdm.schema.yaml'})

    id: str = Field(default=..., description="""The CURIE prefix used for terms in this code system (e.g. “ncbitaxon”, “snomedct”, “icd10cm”).
""", json_schema_extra = { "linkml_meta": {'domain_of': ['CodeSystem', 'ValueSet']} })
    namespace_iri: str = Field(default=..., description="""The base namespace IRI for this ontology, used by OAKlib to expand CURIEs and load the adapter.
""", json_schema_extra = { "linkml_meta": {'domain_of': ['CodeSystem']} })
    version: str = Field(default=..., description="""The release version or publication date of the ontology""", json_schema_extra = { "linkml_meta": {'domain_of': ['CodeSystem']} })
    title: Optional[str] = Field(default=None, description="""A human-readable title for this code system""", json_schema_extra = { "linkml_meta": {'domain_of': ['CodeSystem']} })
    homepage: Optional[str] = Field(default=None, description="""A URL for human browsing or documentation""", json_schema_extra = { "linkml_meta": {'domain_of': ['CodeSystem']} })


class Coding(ConfiguredBaseModel):
    """
    A code + code system reference
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://github.com/BIH-CEI/rd-cdm/linkml/rd_cdm.schema.yaml'})

    system: str = Field(default=..., description="""CURIE for the code system""", json_schema_extra = { "linkml_meta": {'domain_of': ['Coding']} })
    code: str = Field(default=..., description="""The code within the system""", json_schema_extra = { "linkml_meta": {'domain_of': ['Coding']} })
    label: Optional[str] = Field(default=None, description="""The preferred label of the code in its source terminology. This is the string `rd-cdm-validate` compares against the live ontology, so it must track the terminology rather than local presentation preferences.
""", json_schema_extra = { "linkml_meta": {'domain_of': ['Coding', 'ValueSet']} })
    displayLabel: Optional[str] = Field(default=None, description="""An optional presentation label for user interfaces and data capture forms, used where the terminology's preferred label is unhelpful to a data entrant (for example `XX` for `Karyotype 46, XX`). Never validated against the terminology.
""", json_schema_extra = { "linkml_meta": {'domain_of': ['Coding']} })
    status: Optional[CodeStatus] = Field(default=None, description="""Lifecycle of this code against the model's terminology authority. Defaults to `active`. `inactive` records that the code no longer resolves in BioPortal, which is the single authority this model validates against - the RD-CDM does not consult a terminology's own release files, so this is a statement about resolvability, not a claim about why the concept was withdrawn.
An inactive code MUST NOT be offered for new data capture: a generator building a form or dropdown from this value set filters to `active`. It is kept in the value set so that data already captured against it stays interpretable - terminologies do not reuse identifiers, so the code still means exactly what it meant when it was recorded.
""", json_schema_extra = { "linkml_meta": {'domain_of': ['Coding']} })
    replacedBy: Optional[str] = Field(default=None, description="""The CURIE of the active code that a value recorded under an inactive one migrates to. The successor must itself be a member of the same value set, so a legacy value can be migrated without leaving it. Absent where no equivalent has been agreed.
""", json_schema_extra = { "linkml_meta": {'domain_of': ['Coding']} })
    statusNote: Optional[str] = Field(default=None, description="""Why a code carries a non-default status, and what a consumer should do about it. Required in practice for inactive codes.
""", json_schema_extra = { "linkml_meta": {'domain_of': ['Coding']} })


class ValueSet(ConfiguredBaseModel):
    """
    A set of permitted codes for a data element
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://github.com/BIH-CEI/rd-cdm/linkml/rd_cdm.schema.yaml'})

    id: str = Field(default=..., description="""Unique identifier for the value set""", json_schema_extra = { "linkml_meta": {'domain_of': ['CodeSystem', 'ValueSet']} })
    label: str = Field(default=..., description="""Human-readable name""", json_schema_extra = { "linkml_meta": {'domain_of': ['Coding', 'ValueSet']} })
    codes: Optional[list[Coding]] = Field(default=None, description="""List of allowed codes""", json_schema_extra = { "linkml_meta": {'domain_of': ['ValueSet']} })


class DataElement(ConfiguredBaseModel):
    """
    A single data field in the RD-CDM
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://github.com/BIH-CEI/rd-cdm/linkml/rd_cdm.schema.yaml'})

    ordinal: str = Field(default=..., description="""Position within the form or section""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    section: Optional[str] = Field(default=None, description="""Logical grouping or heading""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    elementName: str = Field(default=..., description="""Human-readable name of the element""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    elementCode: Coding = Field(default=..., description="""Primary code describing the element""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    elementCodeSystem: str = Field(default=..., description="""Identifier of the code system (matches one of the `CodeSystem.id` values, e.g. “SNOMEDCT”, “LOINC”, “CustomCode”).""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    dataType: Optional[str] = Field(default=None, description="""Data type (e.g., string, integer, identifier)""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    dataSpecification: Optional[list[str]] = Field(default=None, description="""Reference or link to specification""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    valueSet: Optional[str] = Field(default=None, description="""The `label` of the ValueSet constraining this element - not its `id`. Value set labels are therefore unique, and a value set's `id` is by convention the CURIE of the element it constrains. Both are enforced by `rd_cdm.utils.structure_checks`.
""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    fhirExpression_v4_0_1: Optional[str] = Field(default=None, description="""FHIRPath expression for FHIR mapping""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    recommendedDataSpec_fhir: Optional[str] = Field(default=None, description="""Recommendations for FHIR profiling""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    phenopacketSchemaElement_v2_0: Optional[str] = Field(default=None, description="""Phenopacket schema path""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    recommendedDataSpec_phenopackets: Optional[str] = Field(default=None, description="""Recommended Phenopacket datatype or format""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })
    description: Optional[str] = Field(default=None, description="""Full textual description of the element""", json_schema_extra = { "linkml_meta": {'domain_of': ['DataElement']} })


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
RdCdm.model_rebuild()
CodeSystem.model_rebuild()
Coding.model_rebuild()
ValueSet.model_rebuild()
DataElement.model_rebuild()
