#!/usr/bin/env python3
"""
Generate Python classes from the LinkML schema into:
  src/rd_cdm/python_classes/rd_cdm.py          (LinkML runtime dataclasses)
  src/rd_cdm/python_classes/rd_cdm_pydantic.py  (Pydantic v2 models)
"""
from __future__ import annotations
from pathlib import Path
import sys
import re


def _rewrite_pydantic_config_to_v2(src: str) -> str:
    """Replace Pydantic v1 `class Config:` blocks with v2 `model_config = ConfigDict(...)`."""
    if "ConfigDict" not in src:
        src = src.replace(
            "from pydantic import BaseModel",
            "from pydantic import BaseModel, ConfigDict"
        )
    pattern = re.compile(r"(?ms)^class\s+Config:\n((?:\s+.+\n)+)")

    def repl(m: re.Match) -> str:
        body = m.group(1)
        kwargs = []
        for line in body.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if "=" in stripped:
                k, v = stripped.split("=", 1)
                kwargs.append(f"{k.strip()}={v.strip()}")
        return f"model_config = ConfigDict({', '.join(kwargs)})\n" if kwargs else ""

    return re.sub(pattern, repl, src)


def _write_generated(code_str: str, out_file: Path, schema: Path, generator_name: str) -> bool:
    """Write generated code with a header comment. Returns True on success."""
    header = (
        f"# AUTO-GENERATED by src/rd_cdm/utils/gen_pydantic.py ({generator_name})\n"
        f"# Schema: {schema}\n"
        f"# Do not edit manually — re-run gen_pydantic.py to regenerate.\n\n"
    )
    try:
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(header + code_str, encoding="utf-8")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {out_file}: {e}", file=sys.stderr)
        return False


def main() -> int:
    repo_root = Path(__file__).resolve().parents[3]
    schema = repo_root / "src" / "rd_cdm" / "schema" / "rd_cdm.yaml"
    out_dataclasses = repo_root / "src" / "rd_cdm" / "python_classes" / "rd_cdm.py"
    out_pydantic    = repo_root / "src" / "rd_cdm" / "python_classes" / "rd_cdm_pydantic.py"

    if not schema.exists():
        print(f"ERROR: schema not found at {schema}", file=sys.stderr)
        return 2

    try:
        from linkml.generators.pythongen import PythonGenerator
        from linkml.generators.pydanticgen import PydanticGenerator
    except Exception as e:
        print(
            "ERROR: Could not import LinkML generators. "
            "Is 'linkml' installed? (dev dependency)",
            file=sys.stderr,
        )
        print(f"Details: {e}", file=sys.stderr)
        return 1

    # The schema is generated from directly. Until 2.1.0 it carried a top-level
    # `date:`, which SchemaDefinition rejects, so this ran the generators over a
    # stripped temporary copy - and that workaround is exactly why gen_pydantic
    # succeeded while `linkml validate` and `gen-doc` failed. The date is now an
    # annotation, so there is nothing to strip.
    schema_arg = str(schema)

    # 1) LinkML runtime dataclasses (rd_cdm.py)
    print("Generating LinkML runtime dataclasses...")
    try:
        dataclass_code = PythonGenerator(schema_arg).serialize()
    except Exception as e:
        print("ERROR: Failed to generate LinkML dataclasses.", file=sys.stderr)
        print(f"Details: {e}", file=sys.stderr)
        return 1

    if not _write_generated(dataclass_code, out_dataclasses, schema, "PythonGenerator"):
        return 1
    print(f"✅ LinkML dataclasses written to {out_dataclasses}")

    # 2) Pydantic v2 models (rd_cdm_pydantic.py)
    print("Generating Pydantic v2 models...")
    try:
        pydantic_code = PydanticGenerator(schema_arg).serialize()
        pydantic_code = _rewrite_pydantic_config_to_v2(pydantic_code)
    except Exception as e:
        print("ERROR: Failed to generate Pydantic models.", file=sys.stderr)
        print(f"Details: {e}", file=sys.stderr)
        return 1

    if not _write_generated(pydantic_code, out_pydantic, schema, "PydanticGenerator"):
        return 1
    print(f"✅ Pydantic models written to {out_pydantic}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())