#!/usr/bin/env python3
"""
Generate Python classes from the LinkML schema into:
  src/rd_cdm/python_classes/rd_cdm.py          (LinkML runtime dataclasses)
  src/rd_cdm/python_classes/rd_cdm_pydantic.py  (Pydantic v2 models)
"""
from __future__ import annotations
from pathlib import Path
import sys
import re
import tempfile
import ruamel.yaml

# Top-level fields we added to the schema that are not valid LinkML SchemaDefinition fields
_STRIP_FROM_SCHEMA = {"date"}


def _rewrite_pydantic_config_to_v2(src: str) -> str:
    """Replace Pydantic v1 `class Config:` blocks with v2 `model_config = ConfigDict(...)`."""
    if "ConfigDict" not in src:
        src = src.replace(
            "from pydantic import BaseModel",
            "from pydantic import BaseModel, ConfigDict"
        )
    pattern = re.compile(r"(?ms)^class\s+Config:\n((?:\s+.+\n)+)")

    def repl(m: re.Match) -> str:
        body = m.group(1)
        kwargs = []
        for line in body.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if "=" in stripped:
                k, v = stripped.split("=", 1)
                kwargs.append(f"{k.strip()}={v.strip()}")
        return f"model_config = ConfigDict({', '.join(kwargs)})\n" if kwargs else ""

    return re.sub(pattern, repl, src)


def _write_generated(code_str: str, out_file: Path, schema: Path, generator_name: str) -> bool:
    """Write generated code with a header comment. Returns True on success."""
    header = (
        f"# AUTO-GENERATED by src/rd_cdm/utils/gen_pydantic.py ({generator_name})\n"
        f"# Schema: {schema}\n"
        f"# Do not edit manually — re-run gen_pydantic.py to regenerate.\n\n"
    )
    try:
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(header + code_str, encoding="utf-8")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {out_file}: {e}", file=sys.stderr)
        return False


def main() -> int:
    repo_root = Path(__file__).resolve().parents[3]
    schema = repo_root / "src" / "rd_cdm" / "schema" / "rd_cdm.yaml"
    out_dataclasses = repo_root / "src" / "rd_cdm" / "python_classes" / "rd_cdm.py"
    out_pydantic    = repo_root / "src" / "rd_cdm" / "python_classes" / "rd_cdm_pydantic.py"

    if not schema.exists():
        print(f"ERROR: schema not found at {schema}", file=sys.stderr)
        return 2

    try:
        from linkml.generators.pythongen import PythonGenerator
        from linkml.generators.pydanticgen import PydanticGenerator
    except Exception as e:
        print(
            "ERROR: Could not import LinkML generators. "
            "Is 'linkml' installed? (dev dependency)",
            file=sys.stderr,
        )
        print(f"Details: {e}", file=sys.stderr)
        return 1

    # Strip custom top-level fields that LinkML SchemaDefinition doesn't accept
    yaml = ruamel.yaml.YAML()
    with schema.open("r", encoding="utf-8") as fh:
        schema_data = yaml.load(fh) or {}
    for field in _STRIP_FROM_SCHEMA:
        schema_data.pop(field, None)

    tmp_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".yaml", delete=False, encoding="utf-8"
        ) as tmp:
            yaml.dump(schema_data, tmp)
            tmp_path = tmp.name

        # 1) LinkML runtime dataclasses (rd_cdm.py)
        print("Generating LinkML runtime dataclasses...")
        try:
            python_gen = PythonGenerator(tmp_path)
            dataclass_code = python_gen.serialize()
        except Exception as e:
            print("ERROR: Failed to generate LinkML dataclasses.", file=sys.stderr)
            print(f"Details: {e}", file=sys.stderr)
            return 1

        if not _write_generated(dataclass_code, out_dataclasses, schema, "PythonGenerator"):
            return 1
        print(f"✅ LinkML dataclasses written to {out_dataclasses}")

        # 2) Pydantic v2 models (rd_cdm_pydantic.py)
        print("Generating Pydantic v2 models...")
        try:
            pydantic_gen = PydanticGenerator(tmp_path)
            pydantic_code = pydantic_gen.serialize()
            pydantic_code = _rewrite_pydantic_config_to_v2(pydantic_code)
        except Exception as e:
            print("ERROR: Failed to generate Pydantic models.", file=sys.stderr)
            print(f"Details: {e}", file=sys.stderr)
            return 1

        if not _write_generated(pydantic_code, out_pydantic, schema, "PydanticGenerator"):
            return 1
        print(f"✅ Pydantic models written to {out_pydantic}")

    finally:
        if tmp_path:
            Path(tmp_path).unlink(missing_ok=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())