name: Create and Validate JSON

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install jsonschema

    - name: Create JSON files
      run: |
        python src/parsing/create_codesystems_json.py
        python src/parsing/create_data_elements_json.py
        python src/parsing/create_value_sets_json.py
        python src/parsing/create_rd_cdm_json.py

    - name: Create JSON Status Badge
      run: |
        if python src/parsing/create_rd_cdm_json.py; then
          echo "![RD CDM v2.0.0 JSON](https://img.shields.io/badge/RD%20CDM%20v2.0.0-JSON%20Created%20Successfully-brightgreen)" > json_creation_badge.md
        else
          echo "![RD CDM v2.0.0 JSON](https://img.shields.io/badge/RD%20CDM%20v2.0.0-JSON%20Creation%20Failed-red)" > json_creation_badge.md

    - name: Validate JSON files
      run: |
        python -m jsonschema -i res/v2_0_0_dev0/rd_cdm_data_elements_v2_0_0_dev0.json rd_cdm_v2_0_0_dev0_schema.json
        python -m jsonschema -i res/v2_0_0_dev0/rd_cdm_codesystems_v2_0_0_dev0.json rd_cdm_v2_0_0_dev0_schema.json
        python -m jsonschema -i res/v2_0_0_dev0/rd_cdm_value_sets_v2_0_0_dev0.json rd_cdm_v2_0_0_dev0_schema.json

    - name: Create Validation Badge
      run: |
        if python -m jsonschema -i res/v2_0_0_dev0/rd_cdm_data_elements_v2_0_0_dev0.json rd_cdm_schema_v2_0_0_dev0.json; then
          echo "![RD CDM v2.0.0 Validation](https://img.shields.io/badge/RD%20CDM%20v2.0.0-Validation%20Successful-brightgreen)" > json_validation_badge.md
        else
          echo "![RD CDM v2.0.0 Validation](https://img.shields.io/badge/RD%20CDM%20v2.0.0-Validation%20Failed-red)" > json_validation_badge.md

    - name: Update README with Badges
      run: |
        sed -i '/<!-- PYTHON CI BADGE -->/r json_creation_badge.md' README.md
        sed -i '/<!-- VALIDATION BADGE -->/r json_validation_badge.md' README.md
        rm json_creation_badge.md
        rm json_validation_badge.md

    - name: Commit and Push README update
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update README with JSON creation and validation badges"
        git push
